name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      rendezvous_server:
        description: 'Rendezvous Server'
        required: false
        default: 'jjx.freenas.site'
      rs_pub_key:
        description: 'RS Public Key'
        required: false
        default: '4n1ErBWfZbwVRgSY1t86+VU8J0VeUNrUsvFdXkpXwY8='
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}
      rendezvous_server: ${{ inputs.rendezvous_server || 'jjx.freenas.site' }}
      rs_pub_key: ${{ inputs.rs_pub_key || '4n1ErBWfZbwVRgSY1t86+VU8J0VeUNrUsvFdXkpXwY8=' }}